version: "2"

services:
  nginx:
    build: ./nginx
    links:
      - php
    ports:
      - "8080:80"
    depends_on:
      - php
    networks:
      - server
    volumes:
      - ../news/poliscan/web:/var/www/html/poliscan/web

  php:
    build: ./php
    expose:
      - 9000
    networks:
      - server
    volumes:
      - ../news:/var/www/html

  elasticsearch:
    build: ./elastic
    environment:
      - discovery.type=single-node
    ports:
    - "9200:9200"
    - "9300:9300"
    networks:
      - server
      
  rabbitmq:
    build: ./rabbitmq
    environment:
      - DEFAULT_USER=user
      - DEFAULT_PASS=password
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
        - server

  postgresql:
    build: ./postresql
    ports:
    - "54321:5432"
    environment:
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_USER=postgres
      - POSTGRES_DB=nagg
    volumes:
      - postgresql:/var/lib/postgresql/data
    networks:
      - server
  
  kibana:
    build: ./kibana
    ports:
    - "5601:5601"
    networks:
      - server


volumes:
  data:
    driver: local
  postgresql:

networks:
  server:
