version: "3"

services:
  nginx:
    build: ./nginx
    links:
      - php
    ports:
      - "8080:80"
    volumes_from:
      - app
    depends_on:
      - php
    networks:
      - server

  php:
    build: ./php
    expose:
      - 9000
    volumes_from:
      - app
    networks:
      - server

  elasticsearch:
    build: ./elastic
    environment:
      - discovery.type=single-node
    ports:
    - "9200:9200"
    - "9300:9300"
    volumes_from:
      - app
    networks:
      - server
      
  rabbitmq:
    build: ./rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "15672:15672"
    volumes_from:
      - app
    networks:
        - server

  postgresql:
    build: ./postresql
    ports:
    - "54321:5432"
    environment:
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_USER=postgres
      - POSTGRES_DB=nagg
    volumes_from:
      - app
    volumes:
      - postgresql:/var/lib/postgresql/data
    networks:
      - server

  app:
    image: php:7.2-fpm
    volumes:
      - ../news:/var/www/html
    command: "true"

volumes:
  data:
    driver: local
  postgresql:

networks:
  server:
